# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MemoAppWithRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCoreData'
    # Pods for MemoAppWithRxSwift

  target 'MemoAppWithRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemoAppWithRxSwiftUITests' do
    # Pods for testing
  end

end
